### ISSUE TITLE
Add SVN and Mercurial

### ISSUE THREAD

**Issue by tautology0** [davtur19/DotGit#1]
I've had extractors for git, svn and mercurial (which preceded those of Internetwache.org by a couple of years). It would be simple to check for these directories too, my code to extract all these (in perl):

https://github.com/tautology0/ayfabtu

This is written up (for git): https://www.pentestpartners.com/security-blog/git-extraction-abusing-version-control-systems/ which links to other articles I wrote for svn and mercurial.

**Comment by davtur19** [comment]
I already know svn and mercurial and I had already thought about implementing them but I didn't do it for these reasons:
- I don't know them enough to implement it
- They are less used than git
- I have little knowledge of js and i don't like to develop with it
- The extension would make more requests for each domain visited

Also for these reasons it would take me too long to implement it, maybe in the future I could do it.
(The main reason is that I don't want to spend too much time implementing all this stuff, as I think they are less important)

If you want, you can make a pull request, they are always welcome.

**Comment by davtur19** [comment]
I have updated DotGit and now it supports svn and mercurial, it just does a check and doesn't download them.
By default they are disabled, just go to the settings and activate them.
