### ISSUE TITLE
DotGit not showing full sized in Brave Browser

### ISSUE THREAD

**Issue by ndeepak** [davtur19/DotGit#13]
I cannot see the full results and size of DotGit layout as in Chrome Browser.
In chrome:
![image](https://github.com/davtur19/DotGit/assets/79294472/c13151ac-69a2-465f-a60c-c79c5aa312d4)

But in Brave browser:
![image](https://github.com/davtur19/DotGit/assets/79294472/b70208aa-5589-48ff-9219-758d14c9c2a9)
 
Anyone getting the same issue?
I tried many things but couldnt resolve it. 
Anyone have the solution for it?

**Comment by pdlopez** [comment]
Hello,


I am having the same issue in Chrome 116.0.5845.97 (64 bits)

![image](https://github.com/davtur19/DotGit/assets/107931905/5dc7a43a-c6d2-4c80-9049-d8eedfcaf44e)

**Comment by ndeepak** [comment]
> Hello,
> 
> I am having the same issue in Chrome 116.0.5845.97 (64 bits)
> 
> ![image](https://user-images.githubusercontent.com/107931905/262356598-5dc7a43a-c6d2-4c80-9049-d8eedfcaf44e.png)

I thinks, your permission might be dealing with it, I tweaks some permissions in Chrome, and it solved but couldnt do in Brave

**Comment by davtur19** [comment]
In a few hours/days the update should be available on chrome store, as soon as they approve the update.

If you can't wait, you can download the version from the [releases](https://github.com/davtur19/DotGit/releases), but it will not match the package signature, alternatively you can use Firefox.
