### ISSUE TITLE
dotgit and librewolf

### ISSUE THREAD

**Issue by ghost** [davtur19/DotGit#18]
Hi there,

I’ve noticed that dotgit doesn’t work properly with LibreWolf - it doesn’t seem to detect a git directory. 

I’m not sure why this is happening, but I was hoping you might have some time to look into it or run a test?

**Comment by davtur19** [comment]
Could you give me more information about the directory? (note: dotgit detects them only if they are in the root of the website)

Try to see if it detects them on https://turi.space.

**Comment by ghost** [comment]
> Could you give me more information about the directory? (note: dotgit detects them only if they are in the root of the website)
> 
> Try to see if it detects them on https://turi.space.

Yes, Firefox works well with this plugin, but LibreWolf does not; it doesn’t detect the directories. 

If I try to disable the extension and then enable it again, it works inconsistently. 

The thing is, LibreWolf is essentially Firefox but with telemetry removed and other tools that Firefox uses to collect user information.

**references**:
- <https://librewolf.net/>

**Comment by davtur19** [comment]
Yes, I know what librewolf is, however it shouldn't have anything in particular to make the extension not work....

I tried with the latest version (130.0.1-1) on windows and dotgit works, check that it is not a permissions problem of the extension or that you don't have an old version of the browser.

Also try resetting the extension (the trash button with the x inside the popup of the extension).

**Comment by ghost** [comment]
> Yes, I know what librewolf is, however it shouldn't have anything in particular to make the extension not work....
> 
> I tried with the latest version (130.0.1-1) on windows and dotgit works, check that it is not a permissions problem of the extension or that you don't have an old version of the browser.
> 
> Also try resetting the extension (the trash button with the x inside the popup of the extension).

So, it's strange...I use the last one librewolf on macOS 15.0 (24A335)

Anyway thank you for the answer!

**Comment by davtur19** [comment]
Try to see in about:debugging#/runtime/this-firefox if you see something strange in the debug console of dotgit

**Comment by ghost** [comment]
> Try to see in about:debugging#/runtime/this-firefox if you see something strange in the debug console of dotgit

<img width="666" alt="Screenshot 2024-09-28 at 9 18 33 PM" src="https://github.com/user-attachments/assets/873fcd34-9d17-4d99-b0e0-49121628ce05">

**Comment by davtur19** [comment]
This is "normal" it's a hack for manifest v3, try to click inspect and see the console
