### ISSUE TITLE
Question, re-entering page after clearing list

### ISSUE THREAD

**Issue by ohdudeeee** [davtur19/DotGit#3]
If I have ever previously opened a page with an exposed git folder - DotGit deteced this and when I clear the list and re-entering this same page should exposed git folder message appear whether no?

**Comment by davtur19** [comment]
Yes, the delete button clears the list of sites already visited and sites with the folder exposed
It basically resets everything except the settings

**Comment by ohdudeeee** [comment]
I don't know for what reason but the extension stopped working after cleaning the list, going to page  that was previously detected with exposed git folder doesn't display it on list - even when I manually go to /.git/config file

**Comment by davtur19** [comment]
I identified the problem, I actually introduced a [bug](https://github.com/davtur19/DotGit/commit/2e3e2f283d0b866811aca321fed6130262feb8f4) with the previous fix, the update should be available on the stores within an hour.
Thanks for letting me know.

**Comment by ohdudeeee** [comment]
No problem.

**Comment by ohdudeeee** [comment]
Working now.
