### ISSUE TITLE
Ability to ignore SOME sites?

### ISSUE THREAD

**Issue by xvybihal** [davtur19/DotGit#4]
Hey, would it be possible to add option to ignore some specific sites? For example, dotgit gets me banned from 1password.com if I use it "On all sites" in chrome :/

I would love to add a site blacklist of some form. Those sites should not be scanned when visited.

**Comment by davtur19** [comment]
The site is not scanned twice, after the first visit the site is added to the list of sites not to be scanned (unless you delete all with the button).
So when you realize that the site has blocked you it is already late, and in any case it is no longer visited

**Comment by xvybihal** [comment]
I see, thanks for explaining. I did not realize there is "checked" list of domains in the local storage. :+1: 

I still think it would be beneficial to add something like "ignore" array that user could mangle and add domains ahead, so they get never checked. Am I the only one who would welcome this use case?

**Comment by mritzmann** [comment]
Would also like to have a blacklist, e.g. for `localhost`.

**Comment by davtur19** [comment]
Done
https://github.com/davtur19/DotGit/releases/tag/4.3
