### ISSUE TITLE
Check if git repository is public anyway

### ISSUE THREAD

**Issue by mritzmann** [davtur19/DotGit#7]
```shell
$ curl -s https://bugzilla.kernel.org/.git/config | grep url
	url = https://github.com/bugzilla/bugzilla.git
```

There are Git repositories which are publicly accessible either way.

## Feature Request:

* Parse `.git/config` for `url` and check if the git repository is public or not
* Add a setting to disable notifications if the repo is public either way

With GitHub and GitLab, this could be solved with an HTTP request to the repo.

* `https://github.com/bugzilla/bugzilla 200`: Public
* `https://github.com/bugzilla/bugzilla 404 or 403` Not public

**Comment by davtur19** [comment]
If you notice any problems with this new feature let me know
https://github.com/davtur19/DotGit/releases/tag/4.4
